# wczytaj wszystkie trasy z atrybutów w kontrolerach
controllers:
    resource: ../src/Controller/
    type: attribute

# trasa startowa na /
index:
    path: /
    controller: App\Controller\PhotoController::index

# (zalecane) wczytaj też atrybuty z Kernel.php (np. debug toolbar)
kernel:
    resource: ../src/Kernel.php
    type: attribute
